// THE BUILDER's chat reveal (delight pass, item 1) — the Kaelbot panel's
// conversation MATERIALIZES message by message as the visitor travels
// through the panel's hold, like watching the agent work.
//
// Mechanism (chosen for byte-identity by construction): the staged panel
// texture is the ORIGINAL screenshot, untouched. Nine small "cover patch"
// quads — background-matched fills generated by prepare-assets.mjs's
// chatpatch stage (per-row edge-lerp of the panel's own background, so the
// chat column reads as an empty panel, not redaction bars) — sit a hair in
// front of the panel plane, each hiding one message. As builder-segment
// progress advances, each patch dissolves top-to-bottom (a soft wipe — the
// message underneath streams into existence the way an agent's reply
// does), staggered in conversation rhythm. Once every patch has fully
// dissolved (CHAT_REVEAL_DONE_P, before the first sweep stop of the
// panel's late hold and before the Kaelbot voice line arrives), the quads
// go visible=false and the scene graph renders EXACTLY what it rendered
// before this feature existed — the established rest-frame composition is
// untouched at and past that point, verified byte-for-byte.
//
// Every number below is a pure function of journey t — no clocks, no
// accumulated state (the standing determinism law; DETERMINISM.md gains no
// new exception from this feature).
import CHAT from './chat-messages.json';
import { SEGMENTS } from '../../timeline/segments';
import { builderProgress, panelOpacity } from './builderRig';

export interface ChatMessageRect {
  id: string;
  /** Source-screenshot pixel rect (3024x1980 — chat-messages.json). */
  left: number;
  top: number;
  width: number;
  height: number;
}

export const CHAT_MESSAGES: readonly ChatMessageRect[] = CHAT.messages;
export const CHAT_IMAGE = { width: CHAT.imageWidth, height: CHAT.imageHeight };

/** Where each message's reveal begins, in builder-segment progress p —
 *  conversation rhythm, not a metronome: the user asks, Kael answers after
 *  a beat, the attachment + "Here you go." land quickly, tools fire in
 *  bursts. Starts at the panel's own fadeInEnd (p=0.1: the panel arrives
 *  with its chat column empty) and completes at CHAT_REVEAL_DONE_P. */
export const CHAT_MSG_STARTS: readonly number[] = [
  0.1, 0.15, 0.205, 0.235, 0.285, 0.34, 0.4, 0.455, 0.49,
];

/** Each message's wipe duration in p. */
export const CHAT_MSG_DUR = 0.055;

/** p at (and past) which every patch is fully dissolved. */
export const CHAT_REVEAL_DONE_P =
  CHAT_MSG_STARTS[CHAT_MSG_STARTS.length - 1] + CHAT_MSG_DUR;

/** Journey t at which the reveal completes (must precede the Kaelbot voice
 *  line and the panel's own fade-out — pinned in chatReveal.test.ts). */
export const CHAT_REVEAL_DONE_T =
  SEGMENTS.builder[0] +
  CHAT_REVEAL_DONE_P * (SEGMENTS.builder[1] - SEGMENTS.builder[0]);

const clamp01 = (x: number) => (x < 0 ? 0 : x > 1 ? 1 : x);
const smooth = (x: number) => {
  const t = clamp01(x);
  return t * t * (3 - 2 * t);
};

/** Message i's reveal amount (0 = hidden behind its patch, 1 = fully
 *  materialized) as a pure function of builder progress p. */
export function messageReveal(i: number, p: number): number {
  return smooth((p - CHAT_MSG_STARTS[i]) / CHAT_MSG_DUR);
}

/** The patch quad's own opacity envelope — the kaelbot panel's opacity
 *  (patches ride the panel's fade-in/out exactly) while its message is
 *  still unrevealed; its per-pixel dissolve is the shader's wipe, driven by
 *  messageReveal. */
/** The segment bounds are derived fractions (segments.ts), so a t computed
 *  FROM a p can round-trip a ULP short of it — "done" is judged with this
 *  tolerance so the guarantee below holds at the boundary itself. */
const DONE_EPS = 1e-9;

export function patchOpacity(i: number, t: number): number {
  const reveal = messageReveal(i, builderProgress(t) + DONE_EPS);
  if (reveal >= 1) return 0;
  return panelOpacity('kaelbot', t);
}

/** Whether any patch still needs to render at journey t — the R3F layer's
 *  cheap early-out; past CHAT_REVEAL_DONE_P the quads stop existing as far
 *  as the renderer is concerned and the frame equals the pre-feature one. */
export function anyChatPatchVisible(t: number): boolean {
  if (builderProgress(t) + DONE_EPS >= CHAT_REVEAL_DONE_P) return false;
  return panelOpacity('kaelbot', t) > 0.0005;
}

/** A message rect in panel-UV space (u right, v up — texture convention):
 *  center + size, for placing its patch quad as a child of the unit panel
 *  plane. */
export function messageUvRect(i: number): {
  centerU: number;
  centerV: number;
  sizeU: number;
  sizeV: number;
} {
  const m = CHAT_MESSAGES[i];
  const sizeU = m.width / CHAT_IMAGE.width;
  const sizeV = m.height / CHAT_IMAGE.height;
  const centerU = (m.left + m.width / 2) / CHAT_IMAGE.width;
  const centerV = 1 - (m.top + m.height / 2) / CHAT_IMAGE.height;
  return { centerU, centerV, sizeU, sizeV };
}

export function chatPatchUrl(id: string): string {
  return `/assets/builder/chat/patch-${id}.jpg`;
}
